# Generated by Django 5.1.1 on 2024-12-01 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('client_password', models.CharField(max_length=100)),
                ('over_all_income', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DeductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_amount', models.PositiveIntegerField()),
                ('deduction_date', models.DateTimeField(auto_now_add=True)),
                ('deducted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_actions', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('hours', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('task_percentage', models.PositiveIntegerField()),
                ('progress', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('money_for_task', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('assigned_users', models.ManyToManyField(related_name='developer_tasks', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='fin_app_v2.job')),
            ],
        ),
    ]
