# Generated by Django 5.1.1 on 2025-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0004_crmjob_crmtask_crmtaskcomment_crmtaskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmjob',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен')], default='active', max_length=8, verbose_name='Статус'),
        ),
    ]
